language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

before_script:
  - composer self-update
  - composer install --no-interaction
  
script:
 - vendor/bin/phpunit
 - vendor/bin/phpcs -np src/ tests/
 - vendor/bin/phpstan analyse src/ -l 0