language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

before_script:
  - composer self-update
  - composer install --no-interaction
  
script:
 - phpunit
 - if [[ "$PHPCS" == "1" ]]; then ./vendor/bin/phpcs -np src/ tests/; fi
 - if [[ "$PHPSTAN" == "1" ]]; then ./vendor/bin/phpstan analyse -l 2 src; fi